[phases.setup]
nixPkgs = ["python312", "nodejs_20"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd frontend && npm install && cd .."
]

[phases.build]
cmds = [
  "cd frontend && npm run build && cd .."
]

[start]
cmd = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn soccertrack.wsgi --bind 0.0.0.0:$PORT"
