/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/games/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for games + /api/games/{id}/rollup/ for stat totals. */
        get: operations["games_list"];
        put?: never;
        /** @description CRUD for games + /api/games/{id}/rollup/ for stat totals. */
        post: operations["games_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for games + /api/games/{id}/rollup/ for stat totals. */
        get: operations["games_retrieve"];
        /** @description CRUD for games + /api/games/{id}/rollup/ for stat totals. */
        put: operations["games_update"];
        post?: never;
        /** @description CRUD for games + /api/games/{id}/rollup/ for stat totals. */
        delete: operations["games_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD for games + /api/games/{id}/rollup/ for stat totals. */
        patch: operations["games_partial_update"];
        trace?: never;
    };
    "/api/games/{id}/rollup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for games + /api/games/{id}/rollup/ for stat totals. */
        get: operations["games_rollup_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for roster + /api/players/{id}/minutes/?game={game_id} */
        get: operations["players_list"];
        put?: never;
        /** @description CRUD for roster + /api/players/{id}/minutes/?game={game_id} */
        post: operations["players_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for roster + /api/players/{id}/minutes/?game={game_id} */
        get: operations["players_retrieve"];
        /** @description CRUD for roster + /api/players/{id}/minutes/?game={game_id} */
        put: operations["players_update"];
        post?: never;
        /** @description CRUD for roster + /api/players/{id}/minutes/?game={game_id} */
        delete: operations["players_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD for roster + /api/players/{id}/minutes/?game={game_id} */
        patch: operations["players_partial_update"];
        trace?: never;
    };
    "/api/players/{id}/minutes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for roster + /api/players/{id}/minutes/?game={game_id} */
        get: operations["players_minutes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slots/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for lineup/subbing slots + POST /api/slots/move/. */
        get: operations["slots_list"];
        put?: never;
        /** @description CRUD for lineup/subbing slots + POST /api/slots/move/. */
        post: operations["slots_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slots/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for lineup/subbing slots + POST /api/slots/move/. */
        get: operations["slots_retrieve"];
        /** @description CRUD for lineup/subbing slots + POST /api/slots/move/. */
        put: operations["slots_update"];
        post?: never;
        /** @description CRUD for lineup/subbing slots + POST /api/slots/move/. */
        delete: operations["slots_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD for lineup/subbing slots + POST /api/slots/move/. */
        patch: operations["slots_partial_update"];
        trace?: never;
    };
    "/api/slots/move/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD for lineup/subbing slots + POST /api/slots/move/. */
        post: operations["slots_move_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for stat events + POST /api/stats/undo/. */
        get: operations["stats_list"];
        put?: never;
        /** @description CRUD for stat events + POST /api/stats/undo/. */
        post: operations["stats_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for stat events + POST /api/stats/undo/. */
        get: operations["stats_retrieve"];
        /** @description CRUD for stat events + POST /api/stats/undo/. */
        put: operations["stats_update"];
        post?: never;
        /** @description CRUD for stat events + POST /api/stats/undo/. */
        delete: operations["stats_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD for stat events + POST /api/stats/undo/. */
        patch: operations["stats_partial_update"];
        trace?: never;
    };
    "/api/stats/undo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD for stat events + POST /api/stats/undo/. */
        post: operations["stats_undo_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Game: {
            readonly id: number;
            /** Format: date */
            date: string;
            opponent: string;
            location?: components["schemas"]["LocationEnum"];
        };
        /**
         * @description * `home` - Home
         *     * `away` - Away
         * @enum {string}
         */
        LocationEnum: "home" | "away";
        PatchedGame: {
            readonly id?: number;
            /** Format: date */
            date?: string;
            opponent?: string;
            location?: components["schemas"]["LocationEnum"];
        };
        PatchedPlayer: {
            readonly id?: number;
            name?: string;
            /** Format: int64 */
            jersey_number?: number;
        };
        PatchedPlayerGameSlot: {
            readonly id?: number;
            game?: number;
            readonly player?: components["schemas"]["Player"];
            player_id?: number;
            position?: components["schemas"]["PositionEnum"];
            time_on?: string;
            time_off?: string | null;
        };
        PatchedStatEvent: {
            readonly id?: number;
            game?: number;
            player?: number;
            stat_type?: components["schemas"]["StatTypeEnum"];
            game_time?: string;
            /** Format: date-time */
            readonly created_at?: string;
        };
        Player: {
            readonly id: number;
            name: string;
            /** Format: int64 */
            jersey_number: number;
        };
        PlayerGameSlot: {
            readonly id: number;
            game: number;
            readonly player: components["schemas"]["Player"];
            player_id: number;
            position: components["schemas"]["PositionEnum"];
            time_on: string;
            time_off?: string | null;
        };
        /**
         * @description * `GK` - Goalkeeper
         *     * `LB` - Left Back
         *     * `CB1` - Center Back (Left)
         *     * `CB2` - Center Back (Right)
         *     * `RB` - Right Back
         *     * `LM` - Left Mid
         *     * `CM` - Center Mid
         *     * `RM` - Right Mid
         *     * `LW` - Left Wing
         *     * `ST` - Striker
         *     * `RW` - Right Wing
         * @enum {string}
         */
        PositionEnum: "GK" | "LB" | "CB1" | "CB2" | "RB" | "LM" | "CM" | "RM" | "LW" | "ST" | "RW";
        StatEvent: {
            readonly id: number;
            game: number;
            player: number;
            stat_type: components["schemas"]["StatTypeEnum"];
            game_time: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `Pa` - Pass
         *     * `Cm` - Completed Pass
         *     * `Dr` - Dribble
         *     * `Dw` - Dribble Won
         *     * `Sh` - Shot
         *     * `Fr` - On Frame
         *     * `Gl` - Goal
         *     * `Tk` - Tackle
         * @enum {string}
         */
        StatTypeEnum: "Pa" | "Cm" | "Dr" | "Dw" | "Sh" | "Fr" | "Gl" | "Tk";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    games_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"][];
                };
            };
        };
    };
    games_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Game"];
                "application/x-www-form-urlencoded": components["schemas"]["Game"];
                "multipart/form-data": components["schemas"]["Game"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
        };
    };
    games_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this game. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
        };
    };
    games_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this game. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Game"];
                "application/x-www-form-urlencoded": components["schemas"]["Game"];
                "multipart/form-data": components["schemas"]["Game"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
        };
    };
    games_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this game. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    games_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this game. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedGame"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedGame"];
                "multipart/form-data": components["schemas"]["PatchedGame"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
        };
    };
    games_rollup_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this game. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
        };
    };
    players_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"][];
                };
            };
        };
    };
    players_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Player"];
                "application/x-www-form-urlencoded": components["schemas"]["Player"];
                "multipart/form-data": components["schemas"]["Player"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
        };
    };
    players_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this player. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
        };
    };
    players_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this player. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Player"];
                "application/x-www-form-urlencoded": components["schemas"]["Player"];
                "multipart/form-data": components["schemas"]["Player"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
        };
    };
    players_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this player. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    players_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this player. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPlayer"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPlayer"];
                "multipart/form-data": components["schemas"]["PatchedPlayer"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
        };
    };
    players_minutes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this player. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
        };
    };
    slots_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerGameSlot"][];
                };
            };
        };
    };
    slots_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerGameSlot"];
                "application/x-www-form-urlencoded": components["schemas"]["PlayerGameSlot"];
                "multipart/form-data": components["schemas"]["PlayerGameSlot"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerGameSlot"];
                };
            };
        };
    };
    slots_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this player game slot. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerGameSlot"];
                };
            };
        };
    };
    slots_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this player game slot. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerGameSlot"];
                "application/x-www-form-urlencoded": components["schemas"]["PlayerGameSlot"];
                "multipart/form-data": components["schemas"]["PlayerGameSlot"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerGameSlot"];
                };
            };
        };
    };
    slots_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this player game slot. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    slots_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this player game slot. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPlayerGameSlot"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPlayerGameSlot"];
                "multipart/form-data": components["schemas"]["PatchedPlayerGameSlot"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerGameSlot"];
                };
            };
        };
    };
    slots_move_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerGameSlot"];
                "application/x-www-form-urlencoded": components["schemas"]["PlayerGameSlot"];
                "multipart/form-data": components["schemas"]["PlayerGameSlot"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerGameSlot"];
                };
            };
        };
    };
    stats_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatEvent"][];
                };
            };
        };
    };
    stats_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatEvent"];
                "application/x-www-form-urlencoded": components["schemas"]["StatEvent"];
                "multipart/form-data": components["schemas"]["StatEvent"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatEvent"];
                };
            };
        };
    };
    stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this stat event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatEvent"];
                };
            };
        };
    };
    stats_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this stat event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatEvent"];
                "application/x-www-form-urlencoded": components["schemas"]["StatEvent"];
                "multipart/form-data": components["schemas"]["StatEvent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatEvent"];
                };
            };
        };
    };
    stats_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this stat event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stats_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this stat event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStatEvent"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStatEvent"];
                "multipart/form-data": components["schemas"]["PatchedStatEvent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatEvent"];
                };
            };
        };
    };
    stats_undo_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatEvent"];
                "application/x-www-form-urlencoded": components["schemas"]["StatEvent"];
                "multipart/form-data": components["schemas"]["StatEvent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatEvent"];
                };
            };
        };
    };
}
