# Generated by Django 5.2.13 on 2026-04-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], default='home', max_length=4)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['jersey_number'],
            },
        ),
        migrations.CreateModel(
            name='PlayerGameSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('LB', 'Left Back'), ('CB1', 'Center Back (Left)'), ('CB2', 'Center Back (Right)'), ('RB', 'Right Back'), ('LM', 'Left Mid'), ('CM', 'Center Mid'), ('RM', 'Right Mid'), ('LW', 'Left Wing'), ('ST', 'Striker'), ('RW', 'Right Wing')], max_length=3)),
                ('time_on', models.CharField(max_length=8)),
                ('time_off', models.CharField(blank=True, max_length=8, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='tracker.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='tracker.player')),
            ],
        ),
        migrations.CreateModel(
            name='StatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('Pa', 'Pass'), ('Cm', 'Completed Pass'), ('Dr', 'Dribble'), ('Dw', 'Dribble Won'), ('Sh', 'Shot'), ('Fr', 'On Frame'), ('Gl', 'Goal'), ('Tk', 'Tackle')], max_length=2)),
                ('game_time', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_events', to='tracker.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_events', to='tracker.player')),
            ],
            options={
                'ordering': ['game_time', 'created_at'],
            },
        ),
    ]
