# Generated by Django 6.0.4 on 2026-04-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameslot',
            name='time_off',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playergameslot',
            name='time_on',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='statevent',
            name='game_time',
            field=models.DurationField(),
        ),
        migrations.AddConstraint(
            model_name='playergameslot',
            constraint=models.UniqueConstraint(condition=models.Q(('time_off__isnull', True)), fields=('game', 'position'), name='one_active_player_per_position'),
        ),
        migrations.AddConstraint(
            model_name='playergameslot',
            constraint=models.UniqueConstraint(condition=models.Q(('time_off__isnull', True)), fields=('game', 'player'), name='one_active_slot_per_player'),
        ),
    ]
