# Generated by Django 6.0.4 on 2026-04-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_playergameslot_time_off_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statevent',
            name='stat_type',
            field=models.CharField(choices=[('Pa', 'Pass'), ('Cm', 'Completed Pass'), ('Dr', 'Dribble'), ('Dw', 'Dribble Won'), ('Sh', 'Shot'), ('Fr', 'On Frame'), ('Gl', 'Goal'), ('Tk', 'Tackle'), ('Sv', 'Save')], max_length=2),
        ),
    ]
